### ISSUE TITLE
Get Keys from Bank error

### ISSUE THREAD

**Issue by olivierb2** [Noviat/account_ebics#1]
Dear Noviat,

Thanks for this great module that will save us a lot of time for accounting.

I have an issue during the "Get Keys from Bank" that is returning the following error

    EbicsTechnicalError: [EBICS_AUTHENTICATION_FAILED] Authentifikationssignatur fehlerhaft

You can display the full error here:
https://pastebin.com/wQAZvLKx

We double checked with the Bank, they indicate the EBICS INI Letter has been handled and account should be active on their side.

Any suggestion of how to fix this issue?

Thanks

Olivier.

**Comment by luc-demeyer** [comment]
Which version of the account_ebics module do you use ?
Can you send me a copy of the ebics config parameters ? (you can send it offline to luc.demeyer@noviat.com).

**Comment by olivierb2** [comment]
I'm using version 10.0.1.4.0 (seems not the latest). I will send you a screenshot of my config parameters by mail.

Olivier.

**Comment by olivierb2** [comment]
Dear Luc,

I'm closing this ticket as I'm now pretty sure the issue is not coming from your module. I try to use a small python script that use fintech module and I'm getting the same issue. By Bank is offering a test platform which is working perfectly with this same small script.

I definitely need to look with the bank.

Thanks

Olivier.
