### ISSUE TITLE
Upgrade to Odoo 13

### ISSUE THREAD

**Issue by rpinset** [Noviat/account_ebics#10]
Hello,
Version 13 has turned a lot upside down, especially in accounting.
Is the transition to V13 of this application planned?
Does this app allow the sending of SEPA / XML files using the EBICS protocol to the various banks? The Odoo connection service (via Ponto) does not manage the Banque Populaire Caisse Epargne group (in France).
Cordially

---

Bonjour,
La version 13 a chambouler beaucoup de chose, surtout en comptabilité.
Le passage en V13 de cette application est-elle prévue ?
Cette app permet bien l’envoie de fichier SEPA/XML par protocole EBICS aux différentes banques ? Le service de connexion Odoo (via Ponto) ne gère pas le groupe Banque Populaire Caisse Epargne (en France).
Cordialement

**Comment by rpinset** [comment]
Pour information,

> Bonjour Romaric,
> Merci pour votre message.
> Ponto permet en effet l'envoi de fichier de paiements mais cette fonction n'est pas encore implémentée dans Odoo. Notre équipe dédiée travaille actuellement dessus et nous espérons pouvoir la proposer pour notre version 14. 
> Je vous souhaite une belle journée.
> 
> Bien à vous,
> Jessica Moreaux
> Functional Support Analyst
> Odoo S.A. 

Cette app aurait donc un intérêt pour la version 13 

Merci @luc-demeyer

**Comment by luc-demeyer** [comment]
@romrik 
This module will be ported to Odoo 13 but it's not on top our priority list.
If you are ready to sponsor (part) of the porting effort than we can move faster.
You can contact me offline (luc.demeyer@noviat.com) for this.

**Comment by rpinset** [comment]
Hello, 
Can you send me a screenhost of this page 
Accounting > Configuration > Miscellaneous > EBICS > EBICS Configuration

I discuss your proposal with my hierarchy

Have a good day

**Comment by luc-demeyer** [comment]
Cf. enclosed presentation during Odoo experience 3 years ago.

Screenshots in this presentation are from Odoo 8.0 but except for a small change in look and feel this is still the same.

 

Regards,

Luc

**Comment by rpinset** [comment]
Thanks
I found https://youtu.be/8YwaukCpj1g

**Comment by kurogeek** [comment]
@luc-demeyer , can you create a branch for version 13.0 so that anyone can do a pull request?

**Comment by luc-demeyer** [comment]
@kurogeek 
13.0 branch has now been created (with copy of 12.0 versions of the ebics module but with installabe=False.
I am looking forward to your PR.

**Comment by kurogeek** [comment]
@luc-demeyer #12 
This require the integration test with connection to the bank, however I can't find any sandbox that I can test the module. 

So, normally how do you test it?

**Comment by luc-demeyer** [comment]
You can get such a sandbox from Credit Suisse, cf. https://iso20022test.credit-suisse.com

**Comment by luc-demeyer** [comment]
@kurogeek 
Thanks a lot.
Code review and testing ok.
I merged your work via git format-patch + small security fix, cf. https://github.com/Noviat/account_ebics/commit/6bae2f7c1918dfa7ba602fc84c380987b3e73e4b
