### ISSUE TITLE
Batch download of multiple download file formats

### ISSUE THREAD

**Issue by BT-tbaechle** [Noviat/account_ebics#100]
Hi @luc-demeyer 

Is there a reason why the [format_id field](https://github.com/Noviat/account_ebics/blob/16.0/account_ebics/wizards/ebics_xfer.py#L78-L83) on the ebics.xfer model is just a m2o field instead of m2m? If it were m2m the batch download from `account_ebics_batch` could still download files even if a config has more than one download file format activated. Currently, if you have more than one download file format, the batch download will stop downloading anything as it relies on this [onchange](https://github.com/Noviat/account_ebics/blob/16.0/account_ebics/wizards/ebics_xfer.py#L115C13-L115C13) setting the format_id.

Thanks
Tobias

**Comment by BT-tbaechle** [comment]
After further investigation I found out that if no format_id is selected (by default or manual) all download file formats are considered, so this was not the problem. However, with the batch cron job, if no config is provided the method [looks for a confirmed config matching the user's company](https://github.com/Noviat/account_ebics/blob/16.0/account_ebics_batch/models/ebics_batch_log.py#L83). The problem now it that in a single company setup at least no default company is set when creating a config, hence no config is selected by the batch processing method.

**Comment by luc-demeyer** [comment]
@BT-tbaechle 
you should ensure that the userid used for the batch jobs has sufficient rights and access to all companies for which you have ebics configs.
Odoobot may not have those rights, hence you can give more rights to Odoobot or select another account.

If you want to limit the ebics bartch job to a limited sets of ,configs, than you can configure it.

cf. https://github.com/Noviat/account_ebics/blob/59a85625db8c64d7820a860b345971ce48a325c9/account_ebics_batch/models/ebics_batch_log.py#L73
