### ISSUE TITLE
No Ebics_keys file

### ISSUE THREAD

**Issue by Qchefsdental** [Noviat/account_ebics#109]
We are trying to initialize EBICS but every time 
EBICS Keys Root Directory /etc/odoo/ebics_keys/qpet-main-7264246 is not available.
Please contact your system administrator.

![image](https://github.com/Noviat/account_ebics/assets/110104405/a1ab942b-6e13-4dd4-b3a5-99224839e07c)

Where do we find these Ebics Keys? I tried searching through our directories but I dont see any file that is called Ebics_keys or that contains Ebics keys??

**Comment by Qchefsdental** [comment]
![image](https://github.com/Noviat/account_ebics/assets/110104405/48a72fff-e8fc-457b-8cec-9068a59a1472)


Oh, sorry. Here is the error message.

**Comment by luc-demeyer** [comment]
Imho the error message is clear.
Please pass this error message to your system engineer.

If required we can assist you on a T&M basis to correctly configure this system.
You can contact us via info@noviat.com.

**Comment by Qchefsdental** [comment]
Ok, thanks for the fast response.   I just sent you guys a message to that email.

**Comment by Qchefsdental** [comment]
I just need to know which file contains the keys.  With a simple search I still cant locate them hahaha. 


![image](https://github.com/Noviat/account_ebics/assets/110104405/a53d31a1-f9d4-45e0-b6f0-1548757a6ab1)

**Comment by luc-demeyer** [comment]
Look to the ebics config screen/
