### ISSUE TITLE
"Only admins can upload SVG files" message when non-admin user uploads.

### ISSUE THREAD

**Issue by thsdrouot** [Noviat/account_ebics#11]
Hi everyone,

We get an error when non-admin user is using the protocol to push CSV on Odoo 12. But it works. 

"Only admins can upload SVG files" 

Does anyone encounter the same problem ?

Thanks.

**Comment by luc-demeyer** [comment]
@thsdrouot 
can you give more details (exact scenario of actions taken to reproduce the  problem) ?

**Comment by luc-demeyer** [comment]
closing since no feedback.
