### ISSUE TITLE
Warning due to duplicated labels

### ISSUE THREAD

**Issue by NMisko** [Noviat/account_ebics#20]
I'm getting the following warnings when installing this module:
```
Two fields (upload_fname_dummy, upload_fname) of ebics.xfer() have the same label: Upload Filename.

Two fields (swift_3skey_certificate_fn, ebics_public_bank_keys_fn) of ebics.userid() have the same label: EBICS Public Bank Keys Filename.

Two fields (note_process, note) of ebics.file() have the same label: Notes.
```
I would have liked to quickly fix this via a pull request, but I wasn't sure what to rename the labels to, since both seem to be used.

**Comment by luc-demeyer** [comment]
These field have the same label but they don't create any confusion on the UI hence there is no real issue and hence nothing to be fixed.
