### ISSUE TITLE
EBICS key file error

### ISSUE THREAD

**Issue by matmicro** [Noviat/account_ebics#29]
Hi,

Could you please provide a sample of the EBICS Key file format ?

I have X002 and E002 hash, but i don't succeed to configure the EBICS config to pass initialization.
I am facing JSON error on call to :
```
            keyring = EbicsKeyRing(
                keys=self.ebics_keys,
                passphrase=self.ebics_passphrase)
```

Could you please provide more details on how to fix this ?

Thanks and regards

**Comment by luc-demeyer** [comment]
@matmicro 
A bit a slow response.
You can contact me offline (luc.demeyer@noviat.com) if you are still struggling in getting the connection up and running.
