### ISSUE TITLE
Use fintech ebics confirm_download features

### ISSUE THREAD

**Issue by TeoGoddet** [Noviat/account_ebics#32]
When downloading files, the module should (optionally ?) confirm download,

So thath the bank can send only the needed file when not providing dates.

Correctly explained here
https://www.joonis.de/en/fintech/doc/ebics/confirming_downloads/

client = EbicsClient(...)
docs = client.C53()
client.confirm_download()

When details are decided i can work on a PR

**Comment by luc-demeyer** [comment]
@TeoGoddet 
the confirm_download is already in the code, cf. https://github.com/Noviat/account_ebics/blob/f78c67a037776ceac5623600ea6ece6d065825a0/account_ebics/wizards/ebics_xfer.py#L236

If the bank doesn't know that a recent statement has been downloaded than I suspect that you are running without a fintech license and there are unfortunately serious limitations (not usable for production) without the fintech license key.

**Comment by TeoGoddet** [comment]
Sorry I misread the code and the github search was empty :/, 
I'm having a licence, i'm investigating the problem, it may be incorrectly registered,
