### ISSUE TITLE
Expected singleton - post-migration script

### ISSUE THREAD

**Issue by BT-cjimeno** [Noviat/account_ebics#34]
https://github.com/Noviat/account_ebics/blob/5d2f305764f480b964c6a6df94943557e717bde0/account_ebics/migrations/13.0.1.1/post-migration.py#L30

Good morning, I'm getting the error "Unexpected Singleton" in the line referenced above.
We are migrating from 12.0 to 14.0 and the script is getting run when starting Odoo with the "-u all" option.

I'm not sure if it is a problem of configuration in my customer's data or if it could be more than one occurrencies in the line where the journal is searched.

While debugging, I saw that this only happens with 1 out of the 3 ebics.config that they have, the bank account of one of them is used in two active journals.

**Comment by luc-demeyer** [comment]
@BT-cjimeno 
can you try the following:
replace in line 30;

            'journal_ids': [(6, 0, [journal.id])],
by
            'journal_ids': [(6, 0, journal.ids)],

I'll adapt the code accordingly it this results in a correct migration.

**Comment by BT-cjimeno** [comment]
It worked, thanks!

**Comment by luc-demeyer** [comment]
cf. https://github.com/Noviat/account_ebics/commit/eed09b918468bbfb3b1b25cbbba233a612e18d9b

**Comment by BT-cjimeno** [comment]
Hi @luc-demeyer, the code I tried was different than the one in the commit, I used
`'journal_ids': [(6, 0, journal.ids)]` (as you recommended in the first comment here)
instead of
`'journal_ids': [(6, 0, [journal.ids])]`

Since .ids already returns a list of ids.
Hope it helps, have a nice day.

**Comment by luc-demeyer** [comment]
@BT-cjimeno 
Thanks a lot for remarking this error that I made. I have corrected it in the meawhile.
