### ISSUE TITLE
account_ebics_automation for 12.0?

### ISSUE THREAD

**Issue by jans23** [Noviat/account_ebics#42]
I see that account_ebics_automation ins't available from this repository for 12.0. Before we start migrating it ourself I would like to know if perhaps somebody doesn't have it for 12.0 somewhere separately? I'm asking because, sometimes it happens that work is not pushed.

Also, do you want us to push the migrated module to this repo?

**Comment by luc-demeyer** [comment]
@jans23 
this module is indeed not available for 12.0 and we also have no plans to downgrade this module to 12.0.
There are several major enhancements to the ebics suite after 12.0 hence you may consider upgrading your system to 14.0 or 15.0.
You can of course perform the downgrade yourself or we can do it for you given financial compensation for the development effort.
