### ISSUE TITLE
"state" field there doesn't have "confirm" but "active"

### ISSUE THREAD

**Issue by jans23** [Noviat/account_ebics#44]
```
[
    ("company_ids", "in", self.env.user.company_ids.ids),
    ("state", "=", "confirm"),
]
```

This runs on ebics.config but the state field there doesn't have confirm but active. Despite that filter the code is later checking against the state => was probably

See also this fix for 12.0 [#2d18d396defa0a1b1422552f99a4fcaab63a0f4a](https://github.com/Noviat/account_ebics/pull/43/commits/2d18d396defa0a1b1422552f99a4fcaab63a0f4a)

**Comment by luc-demeyer** [comment]
@jans23 
you are backporting from 14.0
In 14.0 the state field has the 'confirm' state, cf https://github.com/Noviat/account_ebics/blob/4a10e40b33e5a403b2f6f2df2b36f17e8a812a1b/account_ebics/models/ebics_config.py#L132

**Comment by jans23** [comment]
@nikunjantala @fkantelberg for your information.
