### ISSUE TITLE
Bug to fix in ebics_config

### ISSUE THREAD

**Issue by matmicro** [Noviat/account_ebics#62]
There is a bug in the below function : def_update_order_number(self, OrderID)

OderIDs are improperly updated on next :
A00Z is followed by A01Z, A02Z, A03Z, ...
which should be A010, A011, A012... A01Z, A020, A021...

This  leads to reach extremely fast ZZZZ !

File ebics_config.py, line 487 :
Should replace :
```
   if c == 'Z':
      continue

```
By:
```
   if c == 'Z':
      o_list[-i] = '0'
      continue
```

Regards

**Comment by luc-demeyer** [comment]
Thanks a lot for this contribution.
I have applied your suggested patch to account_ebics version 8.0 up to version 16.0.
