### ISSUE TITLE
A button to launch a new HPB request

### ISSUE THREAD

**Issue by thsdrouot** [Noviat/account_ebics#7]
Just a proposal.

Sometimes the banks are refreshing their keys. There is no need to make the process again to validate the new   keys.

Resend an HPB call on request is enough. A button to add would be great and useful for non tech users.

**Comment by luc-demeyer** [comment]
From a security standpoint I prefer a new validation. It's a simple action and I think it's better to verify the refreshed keys with the document received by the bank via an offline method (paper or e-mail).
