### ISSUE TITLE
EBICS v13

### ISSUE THREAD

**Issue by matmicro** [Noviat/account_ebics#99]
Hi, 

I migrate from Odoo 10 to 13.
EBICS module is generating error: 
`
Unknown Error
Traceback (most recent call last):
  File "/odoo/myaddons/account_ebics/wizards/ebics_xfer.py", line 379, in _setup_client
    client = EbicsClient(
  File "<frozen fintech>", line 372, in _checkparams
  File "<frozen fintech.ebics>", line 1722, in __init__
RuntimeError: not all keys available for user xxxxxx
`

Any idea what could cause that issue ?

Regards

**Comment by joonis** [comment]
Does the key file exist?

**Comment by matmicro** [comment]
Yes.
Does v13 require a specific version of fintech ?

**Comment by matmicro** [comment]
FYI i found a fix.
It works fine with fintech==6.4.4 with Odoo 13 python 3.6 / 3.8
It looks failing with recent version of fintech, i don't know why.

**Comment by matmicro** [comment]
Issue was due to version of pip li which works fine with :
cryptography<=39.0.2
fintech==6.4.4

Also path of config files as changed from v10 to v13.

Issue is resolved now.
